from fastapi import FastAPI
from pydantic import BaseModel
from prometheus_client import Counter, generate_latest
from fastapi.responses import Response
from fastapi.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # ✅ SAFE FOR NOW
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ✅ Prometheus metric with labels
incident_requests_total = Counter(
    "incident_requests_total",
    "Total number of incidents",
    ["severity", "service"]
)

class Event(BaseModel):
    source: str
    message: str
    severity: str


@app.get("/")
def home():
    return {"message": "IncidentIQ Backend Running"}


@app.post("/event")
def create_event(event: Event):
    # Increment metric
    incident_requests_total.labels(
        severity=event.severity,
        service=event.source
    ).inc()

    # Static AI analysis
    analysis = {
        "root_cause": "High load caused crash",
        "fix": "Restart service & scale replicas",
        "summary": "Generated by local AI"
    }

    return {
        "event": event.dict(),
        "analysis": analysis,
        "action": f"Auto-remediation triggered for {event.source}",
        "alert": f"Alert sent for {event.source}"
    }


@app.get("/metrics")
def metrics():
    return Response(generate_latest(), media_type="text/plain")


@app.get("/health")
def health():
    return {"status": "ok"}


# ✅ IMPORTANT FOR RENDER DEPLOYMENT
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=False)