from fastapi import FastAPI
from pydantic import BaseModel
from prometheus_client import Counter, generate_latest
from fastapi.responses import Response
from fastapi.middleware.cors import CORSMiddleware
from datetime import datetime

# ✅ INIT APP
app = FastAPI()

# ✅ CORS (required for Vercel frontend)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ✅ PROMETHEUS METRIC
incident_requests_total = Counter(
    "incident_requests_total",
    "Total number of incidents",
    ["severity", "service"]
)

# ✅ IN-MEMORY STORAGE (VERY IMPORTANT)
incidents = []

class Event(BaseModel):
    source: str
    message: str
    severity: str


@app.get("/")
def home():
    return {"message": "IncidentIQ Backend Running"}


# ✅ CREATE INCIDENT
@app.post("/event")
def create_event(event: Event):

    # Prometheus metric
    incident_requests_total.labels(
        severity=event.severity,
        service=event.source
    ).inc()

    # AI analysis (static for now)
    analysis = {
        "root_cause": "High load caused crash",
        "fix": "Restart service & scale replicas",
        "summary": "Generated by local AI"
    }

    incident = {
        "event": event.dict(),
        "analysis": analysis,
        "action": f"Auto-remediation triggered for {event.source}",
        "alert": f"Alert sent for {event.source}",
        "timestamp": datetime.utcnow().isoformat()
    }

    # ✅ STORE INCIDENT
    incidents.append(incident)

    return incident


# ✅ GET ALL INCIDENTS (FRONTEND NEEDS THIS)
@app.get("/incidents")
def get_incidents():
    return incidents


# ✅ PROMETHEUS METRICS
@app.get("/metrics")
def metrics():
    return Response(generate_latest(), media_type="text/plain")


# ✅ HEALTH CHECK
@app.get("/health")
def health():
    return {"status": "ok"}