import os
import requests

OLLAMA_URL = "http://ollama:11434"

def analyze_incident(event):
    try:
        prompt = f"""
You are an SRE expert.

Analyze this incident:
Service: {event['service']}
Issue: {event['issue']}
Severity: {event['severity']}

Provide:
1. Root cause
2. Fix
3. Short summary
"""

        res = requests.post(
            f"{OLLAMA_URL}/api/generate",
            json={
                "model": "llama3",
                "prompt": prompt,
                "stream": False
            },
            timeout=60
        )

        data = res.json()
        output = data.get("response", "")

        return {
            "root_cause": output[:200],
            "fix": "Refer AI analysis",
            "summary": "Generated by local AI"
        }

    except Exception as e:
        return {
            "root_cause": f"AI failed: {str(e)}",
            "fix": "Check Ollama service",
            "summary": "Error occurred"
        }