import React, { useState } from "react";
import "./App.css";
import {
  BarChart, Bar, XAxis, YAxis, Tooltip,
  LineChart, Line, CartesianGrid
} from "recharts";

function App() {
  const [history, setHistory] = useState([]);

  // ✅ Backend URL (NO trailing slash)
  const API = "https://incidentiq-ryxt.onrender.com";

  const triggerIncident = async () => {
    try {
      const severities = ["low", "medium", "high"];
      const randomSeverity = severities[Math.floor(Math.random() * 3)];

      const res = await fetch(`${API}/event`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          source: "kubernetes",
          message: "Pod crash error detected",
          severity: randomSeverity
        })
      });

      // ❗ Handle backend sleep / failure
      if (!res || !res.ok) {
        alert("⚠️ Backend waking up... try again in 30 seconds");
        return;
      }

      let data;
      try {
        data = await res.json();
      } catch (err) {
        console.error("JSON parse error:", err);
        alert("⚠️ Server response error");
        return;
      }

      // ❗ Prevent crash if response is invalid
      if (!data || !data.event || !data.analysis) {
        console.error("Invalid API response:", data);
        alert("⚠️ Invalid backend response");
        return;
      }

      setHistory((prev) => [data, ...prev]);

    } catch (err) {
      console.error("FETCH ERROR:", err);
      alert("⚠️ Backend is sleeping (Render free tier). Wait 30–60 sec.");
    }
  };

  // ✅ Safe severity calculation
  const severityData = [
    { name: "Low", value: history.filter(h => h?.event?.severity === "low").length },
    { name: "Medium", value: history.filter(h => h?.event?.severity === "medium").length },
    { name: "High", value: history.filter(h => h?.event?.severity === "high").length }
  ];

  // ✅ Safe timeline
  const timelineData = history
    .slice()
    .reverse()
    .map((_, i) => ({
      index: i + 1,
      incidents: Math.floor(Math.random() * 5) + 1
    }));

  return (
    <div className="container">
      <h1>🚀 IncidentIQ Dashboard</h1>

      <button onClick={triggerIncident}>Trigger Incident</button>

      {/* CHARTS */}
      <div className="charts">
        <div className="chart">
          <h3>📊 Severity Distribution</h3>
          <BarChart width={400} height={250} data={severityData}>
            <XAxis dataKey="name" />
            <YAxis />
            <Tooltip />
            <Bar dataKey="value" fill="#4CAF50" />
          </BarChart>
        </div>

        <div className="chart">
          <h3>📈 Incident Timeline</h3>
          <LineChart width={500} height={250} data={timelineData}>
            <XAxis dataKey="index" />
            <YAxis />
            <Tooltip />
            <CartesianGrid stroke="#ccc" />
            <Line type="monotone" dataKey="incidents" stroke="#2196F3" />
          </LineChart>
        </div>
      </div>

      {/* AI ANALYSIS */}
      <div className="ai-box">
        <h3>🤖 AI Analysis</h3>
        <p><b>Root Cause:</b> High load caused crash</p>
        <p><b>Fix:</b> Restart service & scale replicas</p>
        <p><b>Summary:</b> Generated by local AI</p>
      </div>

      {/* HISTORY */}
      <div>
        <h2>📜 Incident History</h2>

        {history.length === 0 && (
          <p>No incidents yet. Click "Trigger Incident"</p>
        )}

        {history.map((item, index) => {
          // 🔥 CRASH PROTECTION
          if (!item || !item.event || !item.analysis) return null;

          return (
            <div key={index} className="history-card">
              <p><b>Service:</b> {item.event.source}</p>
              <p><b>Issue:</b> {item.event.message}</p>
              <p><b>Severity:</b> {item.event.severity}</p>
              <p><b>Root Cause:</b> {item.analysis.root_cause}</p>
              <p><b>Fix:</b> {item.analysis.fix}</p>
            </div>
          );
        })}
      </div>
    </div>
  );
}

export default App;